README.md

The ruby links pointed to reggea-python instead of reggea-ruby

Fix links to reggea-ruby in the README

---

bootstrap.sh
minimal_bootstrap.sh

Otherwise both scripts give errors when being run using different shells
bootstrap.sh uses some bash specific features, so sh is not enough.

Add shebang to the scripts

---

payload/reggae/backend/make.d

Makes output less verbose:
```
$ make
[Reggae] Writing reggae source files
[Reggae] Writing reggae configuration
[Reggae] Writing dub configuration
[Reggae] Compiling metabuild binary build.o
[Reggae] Compiling metabuild binary buildgen
[Reggae] Running the created binary to generate the build
[make] Building .reggae/objs/reggae.objs/home/gentleman/dev/dlang/reggae/payload/reggae/backend.o
[make] Building .reggae/objs/reggae.objs/home/gentleman/dev/dlang/reggae/payload/reggae.o
[make] Building .reggae/objs/reggae.objs/home/gentleman/dev/dlang/reggae/payload/reggae/core.o
[make] Building .reggae/objs/reggae.objs/home/gentleman/dev/dlang/reggae/src/reggae.o
[make] Building .reggae/objs/reggae.objs/home/gentleman/dev/dlang/reggae/src/reggae/dub.o
[make] Building …
```

Do not display executed commands (make backend)

---

.travis.yml

Uses `apt` to install ninja and bundler, builds reggae with DMD and LDC. Tests are performed only with dmd.

Better .travis.yml

---

src/reggae/reggae.d
tests/it/runtime/python.d

On Ubuntu (Windows WSL) with a reggaefile.py and the make backend (nothing else tested), python would crash when re-running reggae to change the value of a user-defined variable with the message `TypeError: compile() expected string without null bytes`. Because the reggaefile.py hadn't changed, python used the .pyc file instead of re-interpreting the .py file, which seems to mess something up.
Adding the -B flag to the python call (available in python 2.6+) prevents the creation of the reggaefile.pyc. An alternative is to `export PYTHONDONTWRITEBYTECODE=1` before calling reggae.

Fix python crash when re-running reggae.

---

payload/reggae/dub/info.d
payload/reggae/rules/common.d
payload/reggae/rules/d.d
tests/ut/drules.d

I have a script that generates some files that are then `import`ed into D. So I needed to have object files implicitly depend on targets. Happy to discuss this change/other approaches.

Add implicits argument for objectFile/dlangObjectFiles

---

payload/reggae/rules/d.d
payload/reggae/sorting.d
tests/it/rules/scriptlike.d
tests/it/rules/static_lib.d
tests/it/runtime/dub.d
tests/it/runtime/issues.d
tests/ut/rules/dub.d

Before, when trying to depend on arsd-official, every subpackage
ended up with the same object file name since they're all in
the same directory. Now the package name is used but so are all
the module names in the package being built to avoid this.

Fix #62 - no object file name clashes when building per package

---

payload/reggae/dub/info.d
payload/reggae/options.d
payload/reggae/rules/common.d
payload/reggae/rules/d.d
tests/it/buildgen/optional.d
tests/it/runtime/dub.d

dub build static library dependencies by calling `dmd -lib` on the source files instead of compiling to object files first then calling the archiver. This results in different outputs and different behaviour which can manifest as linker errors. Using dmd's internal archiver, for some reason, seems to produce more lenient binaries that don't complain as much about duplicate or missing symbols.
Fixes #91 and #92.

Mimic how dub builds static library dependencies

---

payload/reggae/dcompile.d
payload/reggae/dependencies.d

On my (fast) Linux box, this brings the build time for the `dcompile` executable down from ~1.35 secs to ~0.6 secs with DMD v2.094.2.
For reggae itself, this means a decrease from 3.6 to 2.9 secs for the 'metabuild' stage (before invoking make).
While at it, perform the -v output parsing of `import` and `file` lines in a single pass.

dcompile: Avoid importing std.regex

---

payload/reggae/backend/ninja.d
tests/ut/cpprules.d
tests/ut/drules.d

`depfile` is already specified in the relevant default rules (and set to `$out.dep`).

Ninja: Remove superfluous DEPFILE parameter for build statements

---

payload/reggae/backend/ninja.d
tests/it/runtime/dub.d
tests/ut/ninja.d

Mimicking `make` (which displays `Building $out`) instead of having Ninja show the command line (usually, some `.reggae/dcompile ...`).
[`ninja -v` can be used to show the invoked commands.]

Ninja: Add descriptions for default rules

---

payload/reggae/dcompile.d

This seems to be enough for proper deps on Windows (tested with ninja).

dcompile: Escape spaces in paths in generated .dep files

---

payload/reggae/backend/ninja.d
payload/reggae/build.d
payload/reggae/dub/info.d
payload/reggae/path.d
payload/reggae/rules/c_and_cpp.d
payload/reggae/rules/common.d
payload/reggae/rules/dub.d
src/reggae/reggae.d
tests/ut/backend/binary.d
tests/ut/build.d
tests/ut/ninja.d

I don't have the full picture of all these path manipulations, but started working on it and tried to simplify it. The basic assumption is that relative paths in reggaefile.d are relative to the project dir, and that those in generated Makefiles and ninja scripts are relative to the build dir.
The dub paths are transformed like this:
```
.reggae\objs\ut.exe.objs\Users\IEUser\AppData\Local\dub\packages\unit-threaded-1.0.11\unit-threaded\source\unit_threaded_attrs_io_light_package.lib
=>
.reggae\objs\ut.exe.objs\__dub__\unit-threaded\source\unit_threaded_attrs_io_light_package.lib
```

Significantly shorten object file/lib paths for dub dependencies (mainly for Windows)

---

payload/reggae/dub/info.d
tests/it/runtime/dub.d

As dub already adds it in that case, and LDC complains about multiple `-fPIC` occurrences (inherited from LLVM…).

Don't add superfluous -fPIC for dub dynamicLibrary builds

---

README.md
payload/reggae/options.d
tests/it/buildgen/backend_errors.d
tests/ut/default_options.d

For a bit less typing for the presumably most common option, working well on Windows too.
`bootstrap.sh` still defaults to `make` (presumably more likely to come preinstalled than `ninja`, on Posix).

Default to the ninja backend

---

payload/reggae/config.d
payload/reggae/dub/info.d
payload/reggae/options.d
src/reggae/json_build.d
tests/ut/options.d

Which comes in handy when e.g. building a reggae cmdline in a script, and extra D flags are to be appended, without overriding previously specified ones.
It also enables specifying D flags containing spaces.

Add --dflag switch as alternative to --dflags

---

dub.json
dub.selections.json
src/reggae/dub/interop/dublib.d

With a significant breaking change - we need to replace the special dub variables in pre/post build commands manually now (see
https://github.com/dlang/dub/pull/2217).

Bump dub to v1.29.0

---

src/reggae/dub/interop/fetch.d

This can shed some light into the error.

dub fetch: Print the name of the package failing to fetch

---

.github/workflows/d.yml
doc/rules.md
dub.json
dub.selections.json
payload/reggae/rules/dub.d
src/reggae/dub/interop/configurations.d
src/reggae/dub/interop/dublib.d
src/reggae/dub/interop/package.d
src/reggae/dub/interop/reggaefile.d
tests/it/runtime/dub.d
tests/it/runtime/issues.d
tests/projects/dub/dub.json
tests/projects/dub/source/main.d
tests/projects/dub/source/test.d
tests/utils.d

`dub test` adds a special test configuration **if** there's either no `unittest` config, or its `targetType` isn't `executable`. That special config is *derived* from the `unittest` (or default) configuration, incl. generating and compiling-in an extra `dub_test_root` module with a `main()` entry point (and an `AliasSeq` of all root project modules). See https://github.com/dlang/dub/pull/2218 for details. That PR landed after the dub v1.29 branch-off, so will land in v1.30. https://github.com/dlang/dub/pull/2288 and https://github.com/dlang/dub/pull/2300 are additionally required for reggae and will land in v1.30 too.

Support dub's actual (and special) `dub test` configuration

---

payload/reggae/dub/info.d
payload/reggae/rules/d.d

This is a dub-specific workaround.

Dub: Filter out implicit `--oq -od=…` dflags for LDC

---

src/reggae/dub/interop/dublib.d
src/reggae/dub/interop/fetch.d
src/reggae/dub/interop/package.d

By avoiding the problematic `reinit` call and instead using 2 `reggae.dub.interop.dublib.Dub` instances - one for the fetch, and another new-from-scratch one after the fetch.

Fix reinit issue after fetching dub packages

---

payload/reggae/dub/interop/dublib.d
payload/reggae/dub/interop/package.d
payload/reggae/rules/dub/external.d
src/reggae/reggae.d

It was taking forever to calculate dependencies for the reggaefile due to `-version=Have_dub`.

Reduce reggae times by making dub dependency lazy

---

src/reggae/reggae.d

The problem with multi-line string literals (used here as file contents, e.g., for `buildgen_main.d`) is that they inherit the newline of the source file. And on Windows, this is governed by git's `autocrlf` setting; `\n` being converted to `\r\n` is the default setting AFAIK.

Windows: Fix superfluous reggae re-runs due to newline diff

---

payload/reggae/rules/common.d
payload/reggae/rules/d.d
src/reggae/reggae.d

This means taking advantage of not always having to calculate the dependency file, and hardly every having to rebuild the reggae code itself due to dub picking up when it needs to build.

Always use dub to build the reggaefile

---

payload/reggae/rules/cmake.d

@kinke stumbled upon this compile error for reggae master, for 32-bit targets (Win32):
```
payload\reggae\rules\cmake.d(98,39): Error: cannot implicitly convert expression `compileGroupIndex` of type `ulong` to `uint`
```

cmakeBuild: Fix build for Win32

---

payload/reggae/dub/interop/dublib.d
payload/reggae/options.d
tests/it/runtime/dub/proper.d

Just like dub does it: https://github.com/dlang/dub/blob/374842d3bf87ce2c00a4f373b8a84b96e2279d33/source/dub/commandline.d#L1341-L1347
This helps especially with a partial `dub.selections.json`, not containing selections for path-based deps (in the .sdl/json), where dub is pretty dumb and can easily take 5 seconds to 'upgrade' those (unless using `--skip-registry=all`, which we cannot do in general).

Only perform 'dub upgrade' if there are missing dub dependencies

---

payload/reggae/dub/interop/dublib.d
payload/reggae/dub/interop/package.d

This works now, as the `dub upgrade` is done via the API; tested manually.

Use a single `dub.dub.Dub` instance

---

payload/reggae/dub/interop/dublib.d
payload/reggae/io.d

For "reasons" it takes ~11ms on my laptop. Before this PR it was called once to get the list of configurations, then again for each one of them.

Only create GeneratorSettings once

---

payload/reggae/rules/dub/external.d
src/reggae/reggae.d
tests/it/runtime/dub/dependencies.d

This was recently changed to absolute paths in f1c098d3e53f87f15e98adfabd97b89a5d3b45a3.

Restore relative output paths for DubPathDependency targets

---

payload/reggae/options.d
payload/reggae/rules/common.d
tests/it/rules/static_lib.d
tests/main.d

Otherwise, a set-up MSVC environment is required for the build too, not just the reggae invocation. cl.exe is already resolved to an absolute path.

Windows: Resolve path to lib.exe (for static libs) at reggae-time

---

payload/reggae/options.d
src/reggae/reggae.d
tests/it/runtime/package.d

The binary backend by default spawns threads for every build, and now we're using it to both calculate the reggafile dependencies (in which threads won't even help), and do compile the build generator from the reggaefile. Since the tests run in threads, it won't be faster and might create the issues that this branch was created to fix. In order to still have a safety net, the horrible Windows version that tries again remains.

Avoid threading issues to begin with
